# Generated by Django 5.0.6 on 2024-08-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='dealer_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
