# Generated by Django 5.0.6 on 2024-08-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0002_vehicles_dealer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='image',
            field=models.CharField(max_length=50),
        ),
    ]
