# Generated by Django 5.0.6 on 2024-08-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0003_alter_vehicles_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
