# Generated by Django 5.0.6 on 2024-08-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0004_remove_orders_is_complete_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='location',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
