# Generated by Django 5.0.6 on 2024-08-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0006_orders_vehicle_image_orders_vehicle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='vehicle_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='vehicle_image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='images',
            field=models.CharField(default='user.png', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
