# Generated by Django 5.0.6 on 2024-08-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0007_orders_vehicle_id_alter_orders_vehicle_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='dealer_name',
        ),
        migrations.AddField(
            model_name='orders',
            name='capacity',
            field=models.CharField(default=2, max_length=2),
            preserve_default=False,
        ),
    ]
